### ISSUE TITLE
Use `[%...]`

### ISSUE THREAD

**Issue by lpw25** [ujamjar/ctypes_of_clang#1]
I spotted this from following the ctypes github. Cool project.

Could I suggest using:

```
[%ccode {| ... |}]
```

instead of:

```
{ccode| ... |ccode}
```

The labels inside of `{...|` are not really meant for marking extensions, they are to allow arbitrary quoting without needing escapes. Whilst there is perhaps not a huge risk of someone wanting to include c code which itself contains the string `|ccode}` it would still be more idiomatic to use `[%ccode {| ... |}]`.

**Comment by andrewray** [comment]
Ok.  I did initially have [%ccode ...] extension points and can put them back.
