### ISSUE TITLE
Completely empty structs are not sealed

### ISSUE THREAD

**Issue by andrewray** [ujamjar/ctypes_of_clang#3]
It's nonsense code, but exists out there.

Not entirely clear how to deal with this.   Ctypes raises an exception if you try to seal the struct.

Some interweb mention of this leading to a non-zero sized struct (with no members) in a platform dependent way. FYI @yallop

**Comment by yallop** [comment]
Yes, I'm not sure of the best way to deal with these.

One tricky point is that it's not obvious what size to give an empty struct.  For example, `gcc` gives empty structs size 0:

```
$ cat s.c
struct t { };
int main(){ return sizeof (struct t); }
$ gcc -ansi  -W -Wall s.c && ./a.out ; echo $?
0
```

while `g++` gives them size 1:

```
$ g++ -ansi  -W -Wall s.c && ./a.out ; echo $?
1
```

(I think, but haven't checked, that empty structs are allowed in C++, but not in C.  I don't know how consistently other C compilers handle empty struct sizes.)

One possible approach is to allow empty structs in ctypes with the code-generating/layout-retrieving implementation ([`Cstubs_structs`](https://github.com/ocamllabs/ocaml-ctypes/blob/master/src/cstubs/cstubs_structs.mli)), and not with the layout-computing implementation ([`Ctypes.structure`](http://ocamllabs.io/ocaml-ctypes/Ctypes_types.TYPE.html#VALstructure), etc.).
