### ISSUE TITLE
Ctypes unsupported argument type

### ISSUE THREAD

**Issue by Lupus** [ujamjar/ctypes_of_clang#4]
I've ran into the following error while trying to bind ev.h from libev:

```
(cd _build/default/clib/stubs && ../stubgen/stubgen.exe -c) > _build/default/clib/stubs/cstubs.c
Fatal error: exception Ctypes_static.Unsupported("Unsupported argument type")
     stubgen clib/stubs/stubs.ml (exit 2)
```

How can I troubleshoot it further? What argument type is causing this?

**Comment by andrewray** [comment]
I've seen this happen when you have an array argument (or return type, or static declaration) ie `void foo(int a[3]);` as this is passed to Ctypes as an array and not converted into a pointer.

To debug, try to run and get the exception location, then track that to the problematic binding(s).  They can then be switched off with an attribute.

**Comment by Lupus** [comment]
I've stumbled across some mailing list that also described array argument as the culprit. I've managed to work around this by filtering the declarations to only the file I currently need by adding `[@includedecls [".*ev.h:.*"]]`.

Can such declarations be filtered out automatically as Ctypes does not support them?

**Comment by andrewray** [comment]
This is arguably a short-coming of ctypes.  A patch to perform a fix up here would be possible, but I am unlikely to add it.
