### ISSUE TITLE
Anonymous enum values

### ISSUE THREAD

**Issue by Lupus** [ujamjar/ctypes_of_clang#5]
Many C libraries, including libev, use anonymous enums for constants, like in [1]. I do not see anything in stubs.c defined for those. Readme in ctypes_of_clang states that enums are supported, though I have not found an example on how to use them.

[1] https://github.com/enki/libev/blob/master/ev.h#L501

**Comment by andrewray** [comment]
Where conversion of the enum value is possible (the values are `constants`), they are converted directly into the ocaml interface ie

```
# #require "ctypes.foreign, ctypes-of-clang.ppx";;
/home/andyman/.opam/4.04.1/lib/ocaml/unix.cma: loaded
/home/andyman/.opam/4.04.1/lib/ocaml/bigarray.cma: loaded
/home/andyman/.opam/4.04.1/lib/bytes: added to search path
/home/andyman/.opam/4.04.1/lib/integers: added to search path
/home/andyman/.opam/4.04.1/lib/integers/integers.cma: loaded
/home/andyman/.opam/4.04.1/lib/integers/integer_printers.cma: loaded
/home/andyman/.opam/4.04.1/lib/ctypes: added to search path
/home/andyman/.opam/4.04.1/lib/ctypes/ctypes.cma: loaded
/home/andyman/.opam/4.04.1/lib/ctypes/ctypes-top.cma: loaded
/home/andyman/.opam/4.04.1/lib/ctypes/ctypes-foreign-base.cma: loaded
/home/andyman/.opam/4.04.1/lib/ctypes/ctypes-foreign-unthreaded.cma: loaded
/home/andyman/.opam/4.04.1/lib/ctypes-of-clang/ppx: added to search path
/home/andyman/.opam/4.04.1/lib/ctypes-of-clang/ppx/./ppx.exe --as-ppx: activated
# let anon_enum = [%ccode {| enum {a = 0x34L,b}; |} ];;
val anon_enum :
  < ctype : Unsigned.uint Ctypes.typ; of_int : int64 -> [> `a | `b ];
    to_int : [< `a | `b ] -> int64 > =
  <obj>
# anon_enum#to_int `a;;
- : int64 = 52L
# anon_enum#to_int `b;;
- : int64 = 53L
# Interrupted.
```

**Comment by Lupus** [comment]
I'm following date example, and I have a test file, similar to [test_date.ml](https://github.com/ujamjar/ctypes_of_clang/blob/master/examples/date/test/test_date.ml), so inside a `%ccode{}` block I have an `#include <ev.h>`, which defines multiple anonymous enums. If I understand it correct, that looks like the following toplevel snippet:

```
# [%ccode {| enum {a = 0x34L,b}; enum {c=42,d};  |} ];;
val anonymous :
  < ctype : Unsigned.uint Ctypes.typ; of_int : int64 -> [> `a | `b ];
    to_int : [< `a | `b ] -> int64 > =
  <obj>
val anonymous_0 :
  < ctype : Unsigned.uint Ctypes.typ; of_int : int64 -> [> `c | `d ];
    to_int : [< `c | `d ] -> int64 > =
  <obj>
```

But I need to know the name of anonymous value to get the integer value, otherwise it fails:
``` 
# anonymous#to_int `a;;
- : int64 = 52L
# anonymous#to_int `d;;
Characters 17-19:
  anonymous#to_int `d;;
                   ^^
Error: This expression has type [> `d ]
       but an expression was expected of type [< `a | `b ]
       The second variant type does not allow tag(s) `d
```

I'm new to OCaml, so sorry if I'm asking something obvious and thanks for your help. :)

**Comment by andrewray** [comment]
(cleaning up a few years later...)

The problem here is the C definition does not provide name, so the compiler has no name to give it.  I dont think there is much that can be done about i.
