### ISSUE TITLE
Support for dune

### ISSUE THREAD

**Issue by Lupus** [ujamjar/ctypes_of_clang#6]
Jbuilder is deprecated, I'm trying to build ctypes_of_clang using dune and can't figure it out. After running `dune upgrade` and running build I'm getting complaints about missing libraries which I do have installed:

```
Error: Library "ocaml-migrate-parsetree" not found.
Error: Library "ppx_tools_versioned" not found.
```

It seems dune automagically supports ocaml-migrate-parsetree based ppx rewriters, but some additional changes need to be done. I tried removing the libraries from dune files, but still can't get past the following:

```
    Error: Failed to create on-demand ppx rewriter for ctypes-of-clang.ppx; no
    ppx driver were found. It seems that ctypes-of-clang.ppx is not compatible
    with Dune. Examples of ppx rewriters that are compatible with Dune are ones
    using ocaml-migrate-parsetree, ppxlib or ppx_driver.
```

Any help greatly appreciated! :)

**Comment by andrewray** [comment]
This stuff was put together in the early days of jbuilder (dune) and will
need a couple of hacks.

I'll try to fix it in the next day or two.

**Comment by Lupus** [comment]
Wow, will be great! Thanks :)

**Comment by andrewray** [comment]
A simple `dune upgrade` seemed to do the trick.  You'll want to `opam install ppx_tools_versioned`

**Comment by Lupus** [comment]
Hm, I'll give it a try. I tried `dune upgrade` in local version of ctypes_of_clang and got into errors. Should `ppx_tools_versioned` be mentioned in opam file in dependencies section?

**Comment by Lupus** [comment]
Got it to build only with the following change applied to `ctypes-of-clang.opam`. Shouldn't these dependencies be listed in .opam file?

```diff
@@ -13,6 +13,8 @@ depends: [
   "dolog"
   "humane-re"
   "ctypes"
+  "ocaml-migrate-parsetree"
+  "ppx_tools_versioned"
 ]
 available: [ ocaml-version >= "4.03.0" ]
 name: "ctypes-of-clang"
```

**Comment by andrewray** [comment]
I've fixed the opam file as well.

**Comment by Lupus** [comment]
Cool! I think this can be closed now. Thanks!
